#!/usr/bin/env zsh

export HISTFILE=$HOME/.zsh_history
export SAVEHIST=100000
export HISTSIZE=10000000
export HISTFILESIZE=20000000

setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "

setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
